In [1]:
import pandas as pd

In [2]:
combined_df = pd.read_csv("../data/cleaned_moderation_data.csv")

In [3]:
combined_df.head()

   label                                               text
0  clean  Go until jurong point, crazy.. Available only ...
1  clean                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3  clean  U dun say so early hor... U c already then say...
4  clean  Nah I don't think he goes to usf, he lives aro...

In [4]:
combined_df.shape

(164740, 2)

In [5]:
combined_df.columns

Index(['label', 'text'], dtype='str')

In [6]:
combined_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 164740 entries, 0 to 164739
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   label   164740 non-null  str
 1   text    164740 non-null  str
dtypes: str(2)
memory usage: 2.5 MB

In [8]:
# text preprocessing
text = "FREE MONEY NOW!!!"
print(text)

# converting to lowercase
text = text.lower()
print(text)

FREE MONEY NOW!!!
free money now!!!

In [9]:
# removing punctuation
import string
text = text.translate(str.maketrans("", "", string.punctuation))
print(text)

free money now

In [10]:
# removing extra whitespace
text = "   free   money   now   "
text = " ".join(text.split())
print(text)

free money now

In [11]:
# creating a resusable function for text preprocessing
def clean_text(text):
    text = text.lower()
    text = text.translate(str.maketrans("", "", string.punctuation))
    text = " ".join(text.split())
    return text

In [12]:
# testing the function
sample = "   FREE   MONEY   NOW!!!   "
print("Before", sample)
print("After", clean_text(sample))

Before    FREE   MONEY   NOW!!!
After free money now

In [13]:
# apply cleaning to entire dataset
combined_df["clean_text"] = combined_df["text"].apply(clean_text)
combined_df[["text", "clean_text"]].head()

,text,clean_text
0,"Go until jurong point, crazy.. Available only ...",go until jurong point crazy available only in ...
1,Ok lar... Joking wif u oni...,ok lar joking wif u oni
2,Free entry in 2 a wkly comp to win FA Cup fina...,free entry in 2 a wkly comp to win fa cup fina...
3,U dun say so early hor... U c already then say...,u dun say so early hor u c already then say
4,"Nah I don't think he goes to usf, he lives aro...",nah i dont think he goes to usf he lives aroun...

In [14]:
# verify that the cleaning worked
combined_df[["text", "clean_text", "label"]].sample(10)

,text,clean_text,label
50638,"Hey TnXman307, I took out the sources linking ...",hey tnxman307 i took out the sources linking t...,clean
25381,There are indeed. I'm still in mourning about ...,there are indeed im still in mourning about ma...,clean
49852,"I would love to, but I haven't been able to fi...",i would love to but i havent been able to find...,clean
155938,I disagree with you. In terms of Glass-Steagal...,i disagree with you in terms of glasssteagal t...,clean
15058,"""\n\n Your repeated efforts to vandalize arti...",your repeated efforts to vandalize articles ma...,clean
115153,Proposed Additions to the Barton Buhtz text.. ...,proposed additions to the barton buhtz text i ...,clean
33954,"""\nAnd thank YOU for the passive-aggression La...",and thank you for the passiveaggression larry ...,clean
100363,REDIRECT Talk:International Orange Chorale of ...,redirect talkinternational orange chorale of s...,clean
105560,United Kingdom | class=Start | importance=Low}...,united kingdom classstart importancelow wikipr...,clean
88760,"""\n\n Opposition, Criticism, or Anti- \n\nWith...",opposition criticism or anti with the exceptio...,clean

In [15]:
(combined_df["clean_text"].str.strip() == "").sum()

np.int64(2)

In [16]:
# removing empty messages
combined_df = combined_df[combined_df["clean_text"].str.strip() != ""].reset_index(drop=True)

In [17]:
(combined_df["clean_text"].str.strip() == "").sum()

np.int64(0)

In [18]:
combined_df.shape

(164738, 3)

In [19]:
# saving preprocessed data to csv
combined_df.to_csv("../data/preprocessed_moderation_data.csv", index=False)